/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import java.awt.Color;

/**
 *
 * @author brikz
 */
public class EscolhaUnidadesTela extends javax.swing.JFrame {

    /**
     * Creates new form EscolhaUnidadesTela
     */
    public EscolhaUnidadesTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jogarU2Botao1 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        SubtituloU2 = new javax.swing.JLabel();
        unidade4EnterBotao = new javax.swing.JLabel();
        unidade2EnterBotao = new javax.swing.JLabel();
        SubtituloU1 = new javax.swing.JLabel();
        SubtituloU3 = new javax.swing.JLabel();
        unidade3EnterBotao = new javax.swing.JLabel();
        SubtituloU4 = new javax.swing.JLabel();
        progressoU1 = new javax.swing.JTextField();
        progressoU3 = new javax.swing.JTextField();
        progressoU2 = new javax.swing.JTextField();
        progressoU4 = new javax.swing.JTextField();
        SubtituloU2b = new javax.swing.JLabel();
        unidade1EnterBotao = new javax.swing.JLabel();
        unidade5EnterBotao = new javax.swing.JLabel();
        unidade6EnterBotao = new javax.swing.JLabel();
        unidade7EnterBotao = new javax.swing.JLabel();
        unidade8EnterBotao = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        SubtituloU5 = new javax.swing.JLabel();
        SubtituloU6 = new javax.swing.JLabel();
        SubtituloU7 = new javax.swing.JLabel();
        SubtituloU8 = new javax.swing.JLabel();
        progressoU5 = new javax.swing.JTextField();
        progressoU6 = new javax.swing.JTextField();
        progressoU7 = new javax.swing.JTextField();
        progressoU8 = new javax.swing.JTextField();
        closeIconPNG = new javax.swing.JButton();

        jogarU2Botao1.setText("Jogar");
        jogarU2Botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarU2Botao1ActionPerformed(evt);
            }
        });

        jTextField8.setBackground(new java.awt.Color(0, 0, 0));
        jTextField8.setFont(new java.awt.Font("Montserrat SemiBold", 1, 36)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(148, 87, 242));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField8.setText("0%");
        jTextField8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(12, 12, 12));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(85, 51, 141));
        jTextField1.setFont(new java.awt.Font("Montserrat", 1, 40)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("SELEÇÃO DE UNIDADE");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jTextField1.setMinimumSize(new java.awt.Dimension(968, 112));
        jTextField1.setPreferredSize(new java.awt.Dimension(968, 59));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(12, 12, 12));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel2.setPreferredSize(new java.awt.Dimension(968, 542));

        SubtituloU2.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        SubtituloU2.setForeground(new java.awt.Color(255, 255, 255));
        SubtituloU2.setText("Arquitetura de SGBD e Modelo ");
        SubtituloU2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubtituloU2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubtituloU2MouseExited(evt);
            }
        });

        unidade4EnterBotao.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        unidade4EnterBotao.setForeground(new java.awt.Color(255, 255, 255));
        unidade4EnterBotao.setText("Unidade 4");
        unidade4EnterBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidade4EnterBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unidade4EnterBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unidade4EnterBotaoMouseExited(evt);
            }
        });

        unidade2EnterBotao.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        unidade2EnterBotao.setForeground(new java.awt.Color(255, 255, 255));
        unidade2EnterBotao.setText("Unidade 2");
        unidade2EnterBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidade2EnterBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unidade2EnterBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unidade2EnterBotaoMouseExited(evt);
            }
        });

        SubtituloU1.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        SubtituloU1.setForeground(new java.awt.Color(255, 255, 255));
        SubtituloU1.setText("Introdução aos DBMS's");
        SubtituloU1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubtituloU1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubtituloU1MouseExited(evt);
            }
        });

        SubtituloU3.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        SubtituloU3.setForeground(new java.awt.Color(255, 255, 255));
        SubtituloU3.setText("Modelo Entidade-Relacionamento");
        SubtituloU3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubtituloU3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubtituloU3MouseExited(evt);
            }
        });

        unidade3EnterBotao.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        unidade3EnterBotao.setForeground(new java.awt.Color(255, 255, 255));
        unidade3EnterBotao.setText("Unidade 3");
        unidade3EnterBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidade3EnterBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unidade3EnterBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unidade3EnterBotaoMouseExited(evt);
            }
        });

        SubtituloU4.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        SubtituloU4.setForeground(new java.awt.Color(255, 255, 255));
        SubtituloU4.setText("Linguagem SQL - DDL");
        SubtituloU4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubtituloU4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubtituloU4MouseExited(evt);
            }
        });

        progressoU1.setEditable(false);
        progressoU1.setBackground(new java.awt.Color(12, 12, 12));
        progressoU1.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        progressoU1.setForeground(new java.awt.Color(255, 255, 255));
        progressoU1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        progressoU1.setText("0%");
        progressoU1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        progressoU1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                progressoU1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                progressoU1MouseExited(evt);
            }
        });

        progressoU3.setEditable(false);
        progressoU3.setBackground(new java.awt.Color(12, 12, 12));
        progressoU3.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        progressoU3.setForeground(new java.awt.Color(255, 255, 255));
        progressoU3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        progressoU3.setText("0%");
        progressoU3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        progressoU3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                progressoU3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                progressoU3MouseExited(evt);
            }
        });

        progressoU2.setEditable(false);
        progressoU2.setBackground(new java.awt.Color(12, 12, 12));
        progressoU2.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        progressoU2.setForeground(new java.awt.Color(255, 255, 255));
        progressoU2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        progressoU2.setText("0%");
        progressoU2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        progressoU2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                progressoU2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                progressoU2MouseExited(evt);
            }
        });

        progressoU4.setEditable(false);
        progressoU4.setBackground(new java.awt.Color(12, 12, 12));
        progressoU4.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        progressoU4.setForeground(new java.awt.Color(255, 255, 255));
        progressoU4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        progressoU4.setText("0%");
        progressoU4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        progressoU4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                progressoU4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                progressoU4MouseExited(evt);
            }
        });

        SubtituloU2b.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        SubtituloU2b.setForeground(new java.awt.Color(255, 255, 255));
        SubtituloU2b.setText("Relacional");
        SubtituloU2b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubtituloU2bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubtituloU2bMouseExited(evt);
            }
        });

        unidade1EnterBotao.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        unidade1EnterBotao.setForeground(new java.awt.Color(255, 255, 255));
        unidade1EnterBotao.setText("Unidade 1");
        unidade1EnterBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidade1EnterBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unidade1EnterBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unidade1EnterBotaoMouseExited(evt);
            }
        });

        unidade5EnterBotao.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        unidade5EnterBotao.setForeground(new java.awt.Color(255, 255, 255));
        unidade5EnterBotao.setText("Unidade 5");
        unidade5EnterBotao.setPreferredSize(new java.awt.Dimension(180, 44));
        unidade5EnterBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidade5EnterBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unidade5EnterBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unidade5EnterBotaoMouseExited(evt);
            }
        });

        unidade6EnterBotao.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        unidade6EnterBotao.setForeground(new java.awt.Color(255, 255, 255));
        unidade6EnterBotao.setText("Unidade 6");
        unidade6EnterBotao.setPreferredSize(new java.awt.Dimension(180, 44));
        unidade6EnterBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidade6EnterBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unidade6EnterBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unidade6EnterBotaoMouseExited(evt);
            }
        });

        unidade7EnterBotao.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        unidade7EnterBotao.setForeground(new java.awt.Color(255, 255, 255));
        unidade7EnterBotao.setText("Unidade 7");
        unidade7EnterBotao.setPreferredSize(new java.awt.Dimension(180, 44));
        unidade7EnterBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidade7EnterBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unidade7EnterBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unidade7EnterBotaoMouseExited(evt);
            }
        });

        unidade8EnterBotao.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        unidade8EnterBotao.setForeground(new java.awt.Color(255, 255, 255));
        unidade8EnterBotao.setText("Unidade 8");
        unidade8EnterBotao.setPreferredSize(new java.awt.Dimension(180, 44));
        unidade8EnterBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidade8EnterBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unidade8EnterBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unidade8EnterBotaoMouseExited(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jSeparator1.setPreferredSize(new java.awt.Dimension(5, 5));

        SubtituloU5.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        SubtituloU5.setForeground(new java.awt.Color(255, 255, 255));
        SubtituloU5.setText("Álgebra Relacional");
        SubtituloU5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubtituloU5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubtituloU5MouseExited(evt);
            }
        });

        SubtituloU6.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        SubtituloU6.setForeground(new java.awt.Color(255, 255, 255));
        SubtituloU6.setText("SQL - DML");
        SubtituloU6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubtituloU6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubtituloU6MouseExited(evt);
            }
        });

        SubtituloU7.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        SubtituloU7.setForeground(new java.awt.Color(255, 255, 255));
        SubtituloU7.setText("Queries Multi-Tabelas");
        SubtituloU7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubtituloU7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubtituloU7MouseExited(evt);
            }
        });

        SubtituloU8.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        SubtituloU8.setForeground(new java.awt.Color(255, 255, 255));
        SubtituloU8.setText("Boas Práticas e Normalização");
        SubtituloU8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubtituloU8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubtituloU8MouseExited(evt);
            }
        });

        progressoU5.setBackground(new java.awt.Color(12, 12, 12));
        progressoU5.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        progressoU5.setForeground(new java.awt.Color(255, 255, 255));
        progressoU5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        progressoU5.setText("0%");
        progressoU5.setBorder(null);
        progressoU5.setMinimumSize(new java.awt.Dimension(93, 49));
        progressoU5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                progressoU5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                progressoU5MouseExited(evt);
            }
        });

        progressoU6.setBackground(new java.awt.Color(12, 12, 12));
        progressoU6.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        progressoU6.setForeground(new java.awt.Color(255, 255, 255));
        progressoU6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        progressoU6.setText("0%");
        progressoU6.setBorder(null);
        progressoU6.setMinimumSize(new java.awt.Dimension(93, 49));
        progressoU6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                progressoU6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                progressoU6MouseExited(evt);
            }
        });

        progressoU7.setBackground(new java.awt.Color(12, 12, 12));
        progressoU7.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        progressoU7.setForeground(new java.awt.Color(255, 255, 255));
        progressoU7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        progressoU7.setText("0%");
        progressoU7.setBorder(null);
        progressoU7.setMinimumSize(new java.awt.Dimension(93, 49));
        progressoU7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                progressoU7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                progressoU7MouseExited(evt);
            }
        });

        progressoU8.setBackground(new java.awt.Color(12, 12, 12));
        progressoU8.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        progressoU8.setForeground(new java.awt.Color(255, 255, 255));
        progressoU8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        progressoU8.setText("0%");
        progressoU8.setBorder(null);
        progressoU8.setMinimumSize(new java.awt.Dimension(93, 49));
        progressoU8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                progressoU8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                progressoU8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubtituloU2b)
                            .addComponent(SubtituloU2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubtituloU3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(unidade3EnterBotao)
                                    .addComponent(unidade2EnterBotao)
                                    .addComponent(unidade4EnterBotao)
                                    .addComponent(SubtituloU1)
                                    .addComponent(unidade1EnterBotao))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(progressoU1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                        .addComponent(progressoU2)
                                        .addComponent(progressoU3))
                                    .addComponent(progressoU4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(SubtituloU4, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SubtituloU8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubtituloU7)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(unidade5EnterBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SubtituloU6)
                                .addComponent(SubtituloU5, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                            .addComponent(unidade6EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unidade7EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unidade8EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progressoU8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(progressoU7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(progressoU6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(progressoU5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(unidade5EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(SubtituloU5)
                                .addGap(31, 31, 31)
                                .addComponent(unidade6EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(SubtituloU6)
                                .addGap(54, 54, 54)
                                .addComponent(unidade7EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(SubtituloU7)
                                .addGap(31, 31, 31)
                                .addComponent(unidade8EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(progressoU5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(progressoU6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(progressoU7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(progressoU8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SubtituloU8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unidade1EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(progressoU1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(SubtituloU1)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unidade2EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(progressoU2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(SubtituloU2)
                        .addGap(2, 2, 2)
                        .addComponent(SubtituloU2b)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unidade3EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(progressoU3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(SubtituloU3)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unidade4EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(progressoU4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SubtituloU4)))
                .addGap(57, 57, 57))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        closeIconPNG.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive - Colégio Santa Cruz\\Documentos\\NetBeansProjects\\ProjetoIntegradorS1\\src\\main\\java\\com\\mycompany\\mavenproject1\\Imagens\\closeIcon.png")); // NOI18N
        closeIconPNG.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        closeIconPNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeIconPNGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(closeIconPNG, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(132, 132, 132))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(closeIconPNG, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jogarU2Botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarU2Botao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jogarU2Botao1ActionPerformed

    private void closeIconPNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeIconPNGActionPerformed
        setVisible(false);
        new MenuPrincipalTela().setVisible(true);
    }//GEN-LAST:event_closeIconPNGActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void unidade1EnterBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade1EnterBotaoMouseEntered
        SubtituloU1.setForeground(new Color(147,87,242));
       	unidade1EnterBotao.setForeground(new Color(147,87,242));
        progressoU1.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_unidade1EnterBotaoMouseEntered

    private void SubtituloU1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtituloU1MouseEntered
	SubtituloU1.setForeground(new Color(147,87,242));
       	unidade1EnterBotao.setForeground(new Color(147,87,242));
        progressoU1.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_SubtituloU1MouseEntered

    private void progressoU1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressoU1MouseEntered
        
	SubtituloU1.setForeground(new Color(147,87,242));
        unidade1EnterBotao.setForeground(new Color(147,87,242));
        progressoU1.setForeground(new Color(147,87,242));

    }//GEN-LAST:event_progressoU1MouseEntered

    private void unidade1EnterBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade1EnterBotaoMouseExited

        SubtituloU2.setForeground(Color.white);
        unidade2EnterBotao.setForeground(Color.white);
        progressoU2.setForeground(Color.white);
    }//GEN-LAST:event_unidade1EnterBotaoMouseExited

    private void progressoU1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressoU1MouseExited
        SubtituloU1.setForeground(Color.white);
        unidade1EnterBotao.setForeground(Color.white);
        progressoU1.setForeground(Color.white);
    }//GEN-LAST:event_progressoU1MouseExited

    private void SubtituloU1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtituloU1MouseExited
        SubtituloU1.setForeground(Color.white);
        unidade1EnterBotao.setForeground(Color.white);
        progressoU1.setForeground(Color.white);
    }//GEN-LAST:event_SubtituloU1MouseExited

    private void unidade1EnterBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade1EnterBotaoMouseClicked
        setVisible(false);
        new U1EnterTela().setVisible(true);
    }//GEN-LAST:event_unidade1EnterBotaoMouseClicked

    private void unidade2EnterBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade2EnterBotaoMouseEntered
        SubtituloU2.setForeground(new Color(147,87,242));
        SubtituloU2b.setForeground(new Color(147,87,242));
        unidade2EnterBotao.setForeground(new Color(147,87,242));
        progressoU2.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_unidade2EnterBotaoMouseEntered

    private void unidade3EnterBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade3EnterBotaoMouseEntered
 	SubtituloU3.setForeground(new Color(147,87,242));
       	unidade3EnterBotao.setForeground(new Color(147,87,242));
        progressoU3.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_unidade3EnterBotaoMouseEntered

    private void unidade4EnterBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade4EnterBotaoMouseEntered
        SubtituloU4.setForeground(new Color(147,87,242));
       	unidade4EnterBotao.setForeground(new Color(147,87,242));
        progressoU4.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_unidade4EnterBotaoMouseEntered

    private void unidade5EnterBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade5EnterBotaoMouseEntered
        SubtituloU5.setForeground(new Color(147,87,242));
       	unidade5EnterBotao.setForeground(new Color(147,87,242));
        progressoU5.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_unidade5EnterBotaoMouseEntered

    private void unidade6EnterBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade6EnterBotaoMouseEntered
        SubtituloU6.setForeground(new Color(147,87,242));
       	unidade6EnterBotao.setForeground(new Color(147,87,242));
        progressoU6.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_unidade6EnterBotaoMouseEntered

    private void unidade7EnterBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade7EnterBotaoMouseEntered
        SubtituloU7.setForeground(new Color(147,87,242));
       	unidade7EnterBotao.setForeground(new Color(147,87,242));
        progressoU7.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_unidade7EnterBotaoMouseEntered

    private void unidade8EnterBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade8EnterBotaoMouseEntered
        SubtituloU8.setForeground(new Color(147,87,242));
       	unidade8EnterBotao.setForeground(new Color(147,87,242));
        progressoU8.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_unidade8EnterBotaoMouseEntered

    private void SubtituloU2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtituloU2MouseEntered
        SubtituloU2.setForeground(new Color(147,87,242));
        SubtituloU2b.setForeground(new Color(147,87,242));
        unidade2EnterBotao.setForeground(new Color(147,87,242));
        progressoU2.setForeground(new Color(147,87,242));

        
    }//GEN-LAST:event_SubtituloU2MouseEntered

    private void SubtituloU2bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtituloU2bMouseEntered
        SubtituloU2.setForeground(new Color(147,87,242));
        SubtituloU2b.setForeground(new Color(147,87,242));
        unidade2EnterBotao.setForeground(new Color(147,87,242));
        progressoU2.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_SubtituloU2bMouseEntered

    private void SubtituloU3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtituloU3MouseEntered
        SubtituloU3.setForeground(new Color(147,87,242));
       	unidade3EnterBotao.setForeground(new Color(147,87,242));
        progressoU3.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_SubtituloU3MouseEntered

    private void SubtituloU4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtituloU4MouseEntered
        SubtituloU4.setForeground(new Color(147,87,242));
       	unidade4EnterBotao.setForeground(new Color(147,87,242));
        progressoU4.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_SubtituloU4MouseEntered

    private void SubtituloU5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtituloU5MouseEntered
        SubtituloU5.setForeground(new Color(147,87,242));
       	unidade5EnterBotao.setForeground(new Color(147,87,242));
        progressoU5.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_SubtituloU5MouseEntered

    private void SubtituloU6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtituloU6MouseEntered
        SubtituloU6.setForeground(new Color(147,87,242));
       	unidade6EnterBotao.setForeground(new Color(147,87,242));
        progressoU6.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_SubtituloU6MouseEntered

    private void SubtituloU7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtituloU7MouseEntered
        SubtituloU7.setForeground(new Color(147,87,242));
       	unidade7EnterBotao.setForeground(new Color(147,87,242));
        progressoU7.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_SubtituloU7MouseEntered

    private void SubtituloU8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtituloU8MouseEntered
        SubtituloU8.setForeground(new Color(147,87,242));
       	unidade8EnterBotao.setForeground(new Color(147,87,242));
        progressoU8.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_SubtituloU8MouseEntered

    private void progressoU2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressoU2MouseEntered
        SubtituloU2.setForeground(new Color(147,87,242));
        SubtituloU2b.setForeground(new Color(147,87,242));
        unidade2EnterBotao.setForeground(new Color(147,87,242));
        progressoU2.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_progressoU2MouseEntered

    private void progressoU3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressoU3MouseEntered
        SubtituloU3.setForeground(new Color(147,87,242));
       	unidade3EnterBotao.setForeground(new Color(147,87,242));
        progressoU3.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_progressoU3MouseEntered

    private void progressoU4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressoU4MouseEntered
        SubtituloU4.setForeground(new Color(147,87,242));
       	unidade4EnterBotao.setForeground(new Color(147,87,242));
        progressoU4.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_progressoU4MouseEntered

    private void progressoU5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressoU5MouseEntered
        SubtituloU5.setForeground(new Color(147,87,242));
       	unidade5EnterBotao.setForeground(new Color(147,87,242));
        progressoU5.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_progressoU5MouseEntered

    private void progressoU6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressoU6MouseEntered
        SubtituloU6.setForeground(new Color(147,87,242));
       	unidade6EnterBotao.setForeground(new Color(147,87,242));
        progressoU6.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_progressoU6MouseEntered

    private void progressoU7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressoU7MouseEntered
        SubtituloU7.setForeground(new Color(147,87,242));
       	unidade7EnterBotao.setForeground(new Color(147,87,242));
        progressoU7.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_progressoU7MouseEntered

    private void progressoU8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressoU8MouseEntered
        SubtituloU8.setForeground(new Color(147,87,242));
       	unidade8EnterBotao.setForeground(new Color(147,87,242));
        progressoU8.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_progressoU8MouseEntered

    private void unidade2EnterBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade2EnterBotaoMouseExited
         unidade2EnterBotao.setForeground(Color.white);
         SubtituloU2.setForeground(Color.white);
        SubtituloU2b.setForeground(Color.white);
        unidade2EnterBotao.setForeground(Color.white);
        progressoU2.setForeground(Color.white);
    }//GEN-LAST:event_unidade2EnterBotaoMouseExited

    private void unidade3EnterBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade3EnterBotaoMouseExited
        SubtituloU3.setForeground(Color.white);
        unidade3EnterBotao.setForeground(Color.white);
        progressoU3.setForeground(Color.white);
    }//GEN-LAST:event_unidade3EnterBotaoMouseExited

    private void unidade4EnterBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade4EnterBotaoMouseExited
        SubtituloU4.setForeground(Color.white);
        unidade4EnterBotao.setForeground(Color.white);
        progressoU4.setForeground(Color.white);
    }//GEN-LAST:event_unidade4EnterBotaoMouseExited

    private void unidade5EnterBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade5EnterBotaoMouseExited
        SubtituloU5.setForeground(Color.white);
        unidade5EnterBotao.setForeground(Color.white);
        progressoU5.setForeground(Color.white);
    }//GEN-LAST:event_unidade5EnterBotaoMouseExited

    private void unidade6EnterBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade6EnterBotaoMouseExited
        SubtituloU6.setForeground(Color.white);
        unidade6EnterBotao.setForeground(Color.white);
        progressoU6.setForeground(Color.white);
    }//GEN-LAST:event_unidade6EnterBotaoMouseExited

    private void unidade7EnterBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade7EnterBotaoMouseExited
        SubtituloU7.setForeground(Color.white);
        unidade7EnterBotao.setForeground(Color.white);
        progressoU7.setForeground(Color.white);
    }//GEN-LAST:event_unidade7EnterBotaoMouseExited

    private void unidade8EnterBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade8EnterBotaoMouseExited
        SubtituloU8.setForeground(Color.white);
        unidade8EnterBotao.setForeground(Color.white);
        progressoU8.setForeground(Color.white);
    }//GEN-LAST:event_unidade8EnterBotaoMouseExited

    private void SubtituloU2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtituloU2MouseExited
        SubtituloU2.setForeground(Color.white);
        unidade2EnterBotao.setForeground(Color.white);
        progressoU2.setForeground(Color.white);
    }//GEN-LAST:event_SubtituloU2MouseExited

    private void SubtituloU2bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtituloU2bMouseExited
        unidade2EnterBotao.setForeground(Color.white);
        SubtituloU2.setForeground(Color.white);
        SubtituloU2b.setForeground(Color.white);
        unidade2EnterBotao.setForeground(Color.white);
        progressoU2.setForeground(Color.white);
    }//GEN-LAST:event_SubtituloU2bMouseExited

    private void SubtituloU3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtituloU3MouseExited
        SubtituloU3.setForeground(Color.white);
        unidade3EnterBotao.setForeground(Color.white);
        progressoU3.setForeground(Color.white);
    }//GEN-LAST:event_SubtituloU3MouseExited

    private void SubtituloU4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtituloU4MouseExited
        SubtituloU4.setForeground(Color.white);
        unidade4EnterBotao.setForeground(Color.white);
        progressoU4.setForeground(Color.white);
    }//GEN-LAST:event_SubtituloU4MouseExited

    private void SubtituloU5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtituloU5MouseExited
        SubtituloU5.setForeground(Color.white);
        unidade5EnterBotao.setForeground(Color.white);
        progressoU5.setForeground(Color.white);
    }//GEN-LAST:event_SubtituloU5MouseExited

    private void SubtituloU6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtituloU6MouseExited
        SubtituloU6.setForeground(Color.white);
        unidade6EnterBotao.setForeground(Color.white);
        progressoU6.setForeground(Color.white);
    }//GEN-LAST:event_SubtituloU6MouseExited

    private void SubtituloU7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtituloU7MouseExited
        SubtituloU7.setForeground(Color.white);
        unidade7EnterBotao.setForeground(Color.white);
        progressoU7.setForeground(Color.white);
    }//GEN-LAST:event_SubtituloU7MouseExited

    private void SubtituloU8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubtituloU8MouseExited
        SubtituloU8.setForeground(Color.white);
        unidade8EnterBotao.setForeground(Color.white);
        progressoU8.setForeground(Color.white);
    }//GEN-LAST:event_SubtituloU8MouseExited

    private void progressoU2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressoU2MouseExited
        unidade2EnterBotao.setForeground(Color.white);
        SubtituloU2.setForeground(Color.white);
        SubtituloU2b.setForeground(Color.white);
        unidade2EnterBotao.setForeground(Color.white);
        progressoU2.setForeground(Color.white);
    }//GEN-LAST:event_progressoU2MouseExited

    private void progressoU3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressoU3MouseExited
        SubtituloU3.setForeground(Color.white);
        unidade3EnterBotao.setForeground(Color.white);
        progressoU3.setForeground(Color.white);
    }//GEN-LAST:event_progressoU3MouseExited

    private void progressoU4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressoU4MouseExited
        SubtituloU4.setForeground(Color.white);
        unidade4EnterBotao.setForeground(Color.white);
        progressoU4.setForeground(Color.white);
    }//GEN-LAST:event_progressoU4MouseExited

    private void progressoU5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressoU5MouseExited
        SubtituloU5.setForeground(Color.white);
        unidade5EnterBotao.setForeground(Color.white);
        progressoU5.setForeground(Color.white);
    }//GEN-LAST:event_progressoU5MouseExited

    private void progressoU6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressoU6MouseExited
        SubtituloU6.setForeground(Color.white);
        unidade6EnterBotao.setForeground(Color.white);
        progressoU6.setForeground(Color.white);
    }//GEN-LAST:event_progressoU6MouseExited

    private void progressoU7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressoU7MouseExited
        SubtituloU7.setForeground(Color.white);
        unidade7EnterBotao.setForeground(Color.white);
        progressoU7.setForeground(Color.white);
    }//GEN-LAST:event_progressoU7MouseExited

    private void progressoU8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressoU8MouseExited
        SubtituloU8.setForeground(Color.white);
        unidade8EnterBotao.setForeground(Color.white);
        progressoU8.setForeground(Color.white);
    }//GEN-LAST:event_progressoU8MouseExited

    private void unidade2EnterBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade2EnterBotaoMouseClicked
        setVisible(false);
        new U2EnterTela().setVisible(true);
    }//GEN-LAST:event_unidade2EnterBotaoMouseClicked

    private void unidade3EnterBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade3EnterBotaoMouseClicked
        setVisible(false);
        new U3EnterTela().setVisible(true);
    }//GEN-LAST:event_unidade3EnterBotaoMouseClicked

    private void unidade4EnterBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade4EnterBotaoMouseClicked
        setVisible(false);
        new U4EnterTela().setVisible(true);
    }//GEN-LAST:event_unidade4EnterBotaoMouseClicked

    private void unidade5EnterBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade5EnterBotaoMouseClicked
        setVisible(false);
        new U5EnterTela().setVisible(true);
    }//GEN-LAST:event_unidade5EnterBotaoMouseClicked

    private void unidade6EnterBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade6EnterBotaoMouseClicked
        setVisible(false);
        new U6EnterTela().setVisible(true);
    }//GEN-LAST:event_unidade6EnterBotaoMouseClicked

    private void unidade7EnterBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade7EnterBotaoMouseClicked
        setVisible(false);
        new U7EnterTela().setVisible(true);
    }//GEN-LAST:event_unidade7EnterBotaoMouseClicked

    private void unidade8EnterBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade8EnterBotaoMouseClicked
        setVisible(false);
        new U8EnterTela().setVisible(true);
    }//GEN-LAST:event_unidade8EnterBotaoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolhaUnidadesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolhaUnidadesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolhaUnidadesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolhaUnidadesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolhaUnidadesTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SubtituloU1;
    private javax.swing.JLabel SubtituloU2;
    private javax.swing.JLabel SubtituloU2b;
    private javax.swing.JLabel SubtituloU3;
    private javax.swing.JLabel SubtituloU4;
    private javax.swing.JLabel SubtituloU5;
    private javax.swing.JLabel SubtituloU6;
    private javax.swing.JLabel SubtituloU7;
    private javax.swing.JLabel SubtituloU8;
    private javax.swing.JButton closeIconPNG;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton jogarU2Botao1;
    private javax.swing.JTextField progressoU1;
    private javax.swing.JTextField progressoU2;
    private javax.swing.JTextField progressoU3;
    private javax.swing.JTextField progressoU4;
    private javax.swing.JTextField progressoU5;
    private javax.swing.JTextField progressoU6;
    private javax.swing.JTextField progressoU7;
    private javax.swing.JTextField progressoU8;
    private javax.swing.JLabel unidade1EnterBotao;
    private javax.swing.JLabel unidade2EnterBotao;
    private javax.swing.JLabel unidade3EnterBotao;
    private javax.swing.JLabel unidade4EnterBotao;
    private javax.swing.JLabel unidade5EnterBotao;
    private javax.swing.JLabel unidade6EnterBotao;
    private javax.swing.JLabel unidade7EnterBotao;
    private javax.swing.JLabel unidade8EnterBotao;
    // End of variables declaration//GEN-END:variables
}
